### ISSUE TITLE
Google Cast not working

### ISSUE THREAD

**Issue by cgapk123** [air-display/apsdk-public#12]
The switch of Google Cast is not turned on and is always gray. I need Google Cast receiver. How can I use it?

**Comment by tishion** [comment]
sorry, not supported feature.

**Comment by cgapk123** [comment]
> sorry, not supported feature.

Request support, I really need this google cast receiver function
I have searched a lot, but I haven't found any similar open source github projects

**Comment by tishion** [comment]
not possible
