### ISSUE TITLE
Windows implementation

### ISSUE THREAD

**Issue by arcticforensics** [air-display/apsdk-public#3]
When Apple iPhone attempts to connect (via screen-mirroring) to the apsdk-demo (Windows x64 build), the connection fails with the follow debug information;
-------------------------------------------------
[DEBUG]Session (00000136595859B0) is waiting
[DEBUG]Media service running on 52192
AP Server started....
[DEBUG]Session (00000136595799D0) accepted and started
[DEBUG]ap_airplay_connection (000001365958ED10) is being created
[DEBUG]Session (000001365958ED10) is waiting
[DEBUG][1332938774992]<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    Request: GET /info RTSP/1.0
    Header:
        Active-Remote: 770433916
        CSeq: 0
        Content-Length: 70
        Content-Type: application/x-apple-binary-plist
        DACP-ID: 47DA36692C2DBA1C
        User-Agent: AirPlay/690.7.1
        X-Apple-ProtocolVersion: 1
    Body:bplist00...Yqualifier..ZtxtAirPlay..................................."
[DEBUG][1332938774992]<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    Request: POST /fp-setup RTSP/1.0
    Header:
        Active-Remote: 770433916
        CSeq: 1
        Content-Length: 16
        Content-Type: application/octet-stream
        DACP-ID: 47DA36692C2DBA1C
        User-Agent: AirPlay/690.7.1
        X-Apple-ET: 32
    Body:FPLY............
[DEBUG]ap_airplay_connection (00000136595799D0) is being destroyed
-------------------------------------------------

Is this because there's an empty fariplay implementation?  I'm only interested in creating a screen-mirroring server.

**Comment by tishion** [comment]
Please look into the readme file
