### ISSUE TITLE
can a " Copyright (c) Sheen Tian (2018-2023) be added to some of your GPLv2 code we wish to reuse in our GPLv3 project?

### ISSUE THREAD

**Issue by fduncanh** [air-display/apsdk-public#6]
@tishion 

I am a developer of the AirPlay server [UxPlay](http://github.com/FDH2/UxPlay), which supports mirror and audio streaming.
We want to add support for HLS video streaming (e.g. YouTube) and your apsdk-public (which we got working) has been very useful as a working example that we could study in action and modify to see how the AirPlay HLS protocol works.

The UxPlay code (mixed C/C++) already contains all the crypto and http support (in C), so the apsdk-public code we propose to initially use is **ap_casting_media_data_store.cpp**,  (plus **ap_casting_media_data_store.h**, and pieces of **utils.cpp**, **utils.h**, **ap_config.h**,  **ap_export.h** that are needed).  This (and its interface to the hlsparse code) will save us from having to understand it fully and reimplement it, at least initially.

I see that you commited the relevant code six years ago, so it is clear you are the original author who can add the copyright notice, which is needed by the GPL.   For our purposes, it would just be needed to be added to **ap_casting_media_data_store.cpp**.   (I can submit a PR to do this, if you wish).  You should also add it to src/ap_server.cpp if you don't want to add it to all files.

* EDIT:  PR #7 to do this has been submitted.

Thank you for you valuable work in  revealing some of  the inner workings of AirPlay video streaming! 

Here is the proposed text of the header:

```
/**
 * apsdk - API for an open-source AirPlay  server
 * Copyright (C) 2018-2023 Sheen Tian
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 */
```

**Comment by tishion** [comment]
Hi @fduncanh , glad to know my project is helpful to you, and yes, I will add headers for all the source files in the Airplay project scope.
